"""Build a synthetic scene for automated tests ONLY.

READ THIS BEFORE USING THE OUTPUT ANYWHERE NEAR A DEMO.

The problem statement forbids showing synthetic SAR as if it were real data, and
it is right to. This file exists for one reason: the test suite has to be able
to run the whole pipeline on a machine with no network and no 40 GB download,
with a known ground truth so assertions can be exact.

Everything it writes is marked `selftest: true` in the scene index, and
`app/scenes.py` hides such scenes from `/api/scenes` unless the operator sets
TIDETRACE_ALLOW_SELFTEST_SCENES=1. Do not show one to a judge.

The raster is a physically shaped stand in, not a pretty picture: Rayleigh
distributed sea clutter at a chosen mean backscatter, a darker elongated slick
with a soft edge, and a rounded low contrast patch that a correct detector
should classify as a look-alike rather than oil.

Usage:
    python scripts/make_selftest_scene.py
    python scripts/make_selftest_scene.py --id my_selftest --size 512
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app import config, scenes as scenes_mod   # noqa: E402
from app.geo import raster as raster_mod       # noqa: E402

DEFAULT_ID = "selftest_synthetic"


def build(size: int = 768, lat0: float = 19.05, lon0: float = 71.60,
          pixel_deg: float = 0.00018, sea_db: float = -21.0,
          seed: int = 20260920) -> dict:
    rng = np.random.default_rng(seed)

    # Rayleigh amplitude speckle gives the right intensity statistics for SAR.
    lin_sea = 10.0 ** (sea_db / 10.0)
    amp = rng.rayleigh(scale=np.sqrt(lin_sea / 2.0), size=(size, size))
    vv_lin = amp ** 2

    yy, xx = np.mgrid[0:size, 0:size].astype(np.float32)
    cy, cx = size * 0.46, size * 0.50

    # Oil: elongated, rotated, sharp edged, strong damping.
    th = np.radians(35.0)
    xr = (xx - cx) * np.cos(th) + (yy - cy) * np.sin(th)
    yr = -(xx - cx) * np.sin(th) + (yy - cy) * np.cos(th)
    slick = np.exp(-((xr / (size * 0.135)) ** 2 + (yr / (size * 0.026)) ** 2) ** 1.6)
    slick = np.clip((slick - 0.16) / 0.84, 0.0, 1.0)

    # Look-alike: round, soft edged, weak damping (low wind cell or biogenic film).
    ly, lx = size * 0.74, size * 0.26
    la = np.exp(-(((xx - lx) / (size * 0.075)) ** 2 + ((yy - ly) / (size * 0.070)) ** 2))
    la = np.clip((la - 0.30) / 0.70, 0.0, 1.0)

    # Oil damps hard, the look-alike damps weakly. The look-alike still has to
    # be dark enough to be picked up as a candidate patch, otherwise the test
    # never exercises the oil versus look-alike decision at all.
    damping = 1.0 - 0.86 * slick - 0.56 * la
    vv_lin = vv_lin * np.clip(damping, 0.02, 1.0)
    vv_db = 10.0 * np.log10(np.maximum(vv_lin, 1e-9)).astype(np.float32)

    vh_db = (vv_db - 12.0 + rng.normal(0.0, 0.8, (size, size))).astype(np.float32)
    stack = np.stack([vv_db, vh_db], axis=0)

    truth = np.zeros((size, size), dtype=np.uint8)
    truth[la > 0.35] = 1
    truth[slick > 0.35] = 2

    transform = (pixel_deg, 0.0, lon0 - pixel_deg * size / 2.0,
                 0.0, -pixel_deg, lat0 + pixel_deg * size / 2.0)
    return {"sar": stack, "truth": truth, "transform": transform}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--id", default=DEFAULT_ID)
    ap.add_argument("--size", type=int, default=768)
    ap.add_argument("--lat", type=float, default=19.05)
    ap.add_argument("--lon", type=float, default=71.60)
    ap.add_argument("--t", default="2024-02-14T05:40:00Z")
    ap.add_argument("--seed", type=int, default=20260920)
    args = ap.parse_args()

    out = build(size=args.size, lat0=args.lat, lon0=args.lon, seed=args.seed)
    sar_path = Path(config.SAR_DIR) / ("%s.tif" % args.id)
    mask_path = Path(config.SAR_DIR) / ("%s_mask.tif" % args.id)

    raster_mod.write_geotiff(sar_path, out["sar"], out["transform"], "EPSG:4326")
    # The mask is written WITHOUT a transform on purpose, to exercise the rule
    # that georeference must be copied from the SAR image before any lat/lon maths.
    raster_mod.write_geotiff(mask_path, out["truth"].astype(np.uint8),
                             (1.0, 0.0, 0.0, 0.0, -1.0, 0.0), "EPSG:4326")

    scene = scenes_mod.describe_geotiff(
        sar_path, scene_id=args.id,
        title="SELF TEST synthetic scene, not for demonstration",
        t_sat=args.t, mask_path=mask_path,
        source="synthetic, generated by scripts/make_selftest_scene.py",
        license_="n/a",
        selftest=True,
        notes="Synthetic raster for automated tests. Never show this to a judge.",
    )
    scenes_mod.upsert([scene])

    print("wrote %s (%.1f MB) and %s" % (sar_path.name, sar_path.stat().st_size / 1e6,
                                         mask_path.name))
    print("scene %s marked selftest, hidden from /api/scenes by default" % scene.id)
    print("bounds %s  centroid %s  ais_mode %s"
          % ([round(v, 4) for v in scene.bounds], scene.centroid, scene.ais_mode))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
